#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1

start_service() {
	[ -f /mnt/mmcblk0p24/er1-upgrade/pending-packages ] || return 0

	procd_open_instance
	procd_set_param command /usr/sbin/er1-upgrade restore --auto
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param term_timeout 5
	procd_close_instance
}
